      PROGRAM CRTPNT
        IMPLICIT NONE
        INTEGER SEED,NPOINTS,I
        CHARACTER*16 FNAME
        PARAMETER(SEED = 86456)
        PRINT *,'ENTER THE NUMBER OF POINTS'
        READ *,NPOINTS
        PRINT *,'SELECT FILE NAME'
        READ *,FNAME
        CALL SRAND(SEED)
        OPEN(UNIT=11,FILE=FNAME,STATUS='UNKNOWN')
        WRITE(11,'(I8)')NPOINTS
        DO 10,I=1,NPOINTS
            WRITE(11,'(F10.4)')RAND()*1000
10      CONTINUE
        CLOSE(UNIT=11,STATUS='KEEP')
      END
