C COMPUTE AVERAGE MARKS OF STUDENTS
      PROGRAM MARKS
	IMPLICIT NONE
        INTEGER I,NENTR,NSTUD,NSUBJ,GETNEN
        REAL AVGMRK,AVGALL
        CHARACTER*32 STUD(100)
        CHARACTER*16 TN,SN
        CHARACTER*16 NAME(100),SRNAM(100)
        CHARACTER*16 SUBJ(100)
        INTEGER MARK(100)
        COMMON /MRKENT/ NAME,SRNAM,SUBJ,MARK,NENTR
        CALL ISTDL
        CALL LODFIL
        PRINT *,'n. of read eantries = ',GETNEN()
        CALL PRENT
        CALL STDLIS(STUD,NSTUD)
        PRINT *,'n. of students = ',NSTUD
        PRINT *,'n. Name             Surname         Average'
        DO 10,I=1,NSTUD
          TN=STUD(I)(1:17)
          SN=STUD(I)(17:32)
          WRITE(*,100) I,' ',TN,' ',SN,' ',AVGMRK(TN,SN)
10      CONTINUE
        WRITE(*,200) 'Average mark for all subjects/students = '
     & ,AVGALL()
100   FORMAT(I3,A1,A,A1,A,A1,F6.2)
200   FORMAT(A,F6.2)
      END
C CREATE STUDENTS LIST
      SUBROUTINE STDLIS(STUD,NSTUD)
        CHARACTER*32 STUD(100)
        LOGICAL IN
        INTEGER I,J,NSTUD
        CHARACTER*16 BLANK
        CHARACTER*16 NAME(100),SRNAM(100)
        CHARACTER*16 SUBJ(100)
        INTEGER MARK(100)
        COMMON /MRKENT/ NAME,SRNAM,SUBJ,MARK,NENTR
	NSTUD=0
        DO 10,I=1,100
          IF(I.EQ.1) THEN 
            STUD(I)(1:16)=NAME(I)
            STUD(I)(17:32)=SRNAM(I)
	    NSTUD=NSTUD+1
          END IF
          IN=.FALSE.
          DO 20,J=1,NSTUD
            IF ((NAME(I).EQ.'NULL').AND.(SRNAM(I).EQ.'NULL')) IN=.TRUE.
            IF((STUD(J)(1:16).EQ.NAME(I)).AND.
     & (STUD(J)(17:32).EQ.SRNAM(I))) IN=.TRUE.
20        CONTINUE
        IF(.NOT.IN) THEN
          NSTUD=NSTUD+1
          STUD(NSTUD)(1:16)=NAME(I)
          STUD(NSTUD)(17:32)=SRNAM(I)
        END IF        
10      CONTINUE
      END
C RETURN THE NUMBER OF ENTRIES READ
      INTEGER FUNCTION GETNEN()
	IMPLICIT NONE
        INTEGER I,NENTR
        CHARACTER*16 NAME(100),SRNAM(100)
        CHARACTER*16 SUBJ(100)
        INTEGER MARK(100)
        COMMON /MRKENT/ NAME,SRNAM,SUBJ,MARK,NENTR
        GETNEN=NENTR
        RETURN
      END
C INITIALIZE ENTRIES LIST
      SUBROUTINE ISTDL
	IMPLICIT NONE
        INTEGER I,NENTR
        CHARACTER*16 NAME(100),SRNAM(100)
        CHARACTER*16 SUBJ(100)
        INTEGER MARK(100)
        COMMON /MRKENT/ NAME,SRNAM,SUBJ,MARK,NENTR
        DO 10,I=1,100
          NAME(I)='NULL'
          SRNAM(I)='NULL'
10      CONTINUE
      END
C LOAD DATA FROM FILE
      SUBROUTINE LODFIL
	IMPLICIT NONE
        INTEGER I,NENTR
        CHARACTER*16 NAME(100),SRNAM(100)
        CHARACTER*16 SUBJ(100)
        INTEGER MARK(100)
        COMMON /MRKENT/ NAME,SRNAM,SUBJ,MARK,NENTR
        NENTR=0
	OPEN(11,FILE='stdmks.txt')
        DO 10,I=1,100
	  READ(11,*,END=20) NAME(I),SRNAM(I),SUBJ(I),MARK(I)
          NENTR=NENTR+1
10      CONTINUE
20      CLOSE(11)
      END
C GIVE THE AVERAGE MARK FOR ALL THE STUDENTS
      REAL FUNCTION AVGALL()
        IMPLICIT NONE
        INTEGER I,NENTR,MSUM,NPS
        CHARACTER*16 NAME(100),SRNAM(100)
        CHARACTER*16 SUBJ(100)
        INTEGER MARK(100)
        COMMON /MRKENT/ NAME,SRNAM,SUBJ,MARK,NENTR
        MSUM=0
        DO 10,I=1,NENTR
            MSUM=MSUM+MARK(I)
10      CONTINUE
        AVGALL=REAL(MSUM)/REAL(NENTR)
        RETURN        
      END
C PRINT ALL MARKS ENTRIES
      SUBROUTINE PRENT
        IMPLICIT NONE
        INTEGER I,NENTR
        CHARACTER*16 NAME(100),SRNAM(100)
        CHARACTER*16 SUBJ(100)
        INTEGER MARK(100)
        COMMON /MRKENT/ NAME,SRNAM,SUBJ,MARK,NENTR
        PRINT *,'Name',' Surname',' Subject',' Mark'
        DO 10,I=1,NENTR
          PRINT *,I,NAME(I),SRNAM(I),SUBJ(I),MARK(I)
10      CONTINUE
      END
C GET AVERAGE MARK OF A GIVEN STUDENT
      REAL FUNCTION AVGMRK(NAM,SRN)
        IMPLICIT NONE
C NPS N. OF ENTRIES FOR A GIVEN STUDENT
        CHARACTER*16 NAM,SRN
        INTEGER I,N,NENTR,MSUM,NPS
        CHARACTER*16 NAME(100),SRNAM(100)
        CHARACTER*16 SUBJ(100)
        INTEGER MARK(100)
        COMMON /MRKENT/ NAME,SRNAM,SUBJ,MARK,NENTR
        MSUM=0
        N=0
        DO 10,I=1,NENTR
          IF((NAME(I).EQ.NAM).AND.(SRNAM(I).EQ.SRN)) THEN
            MSUM=MSUM+MARK(I)
            N=N+1
          ENDIF
10      CONTINUE
        AVGMRK=REAL(MSUM)/REAL(N)
        RETURN
      END
