      SUBROUTINE MNSD2(X,NPOINTS,AVG,SD2)
        IMPLICIT NONE
        INTEGER NPOINTS,I
        REAL X(1000),MSUM,MSUMSQ,AVG,SD,MVAR,SD2
        MSUM = 0.0
        MSUMSQ = 0.0
        DO 10,I=1,NPOINTS
            MSUM=MSUM+X(I)
            MSUMSQ=MSUMSQ+X(I)**2
10      CONTINUE
        AVG=MSUM/NPOINTS
        SD=SQRT(MSUMSQ - NPOINTS*AVG)/(NPOINTS-1)
        MVAR=0.0
        DO 20,I=1,NPOINTS
            MVAR=(X(I)-AVG)**2+MVAR
20      CONTINUE
        PRINT *,'MVAR = ',MVAR
        PRINT *,'MVAR/NPOINTS ',MVAR/NPOINTS
C        SD2=SQRT((MSUMSQ/AVG)-AVG*AVG)
        SD2=SQRT(MVAR/NPOINTS)
      END

      SUBROUTINE MEANSD(X,NPOINTS,AVG,SD)
        IMPLICIT NONE
        INTEGER NPOINTS,I
        REAL X(1000),MSUM,MSUMSQ,AVG,SD
        MSUM = 0.0
        MSUMSQ = 0.0
        DO 10,I=1,NPOINTS
            MSUM=MSUM+X(I)
            MSUMSQ=MSUMSQ+X(I)**2
10      CONTINUE
        AVG=MSUM/NPOINTS
        SD=SQRT(MSUMSQ - NPOINTS*AVG)/(NPOINTS-1)
      END
C main program
      PROGRAM STATS
        IMPLICIT NONE
        CHARACTER FNAME*16
C MAX N. OF POINTS ALLOWED IS 1000
        REAL X(1000),AVG,SD
        INTEGER NPOINTS,I
10      WRITE(*,*)'ENTER DATA FILE NAME'
        READ(*,*)FNAME
        OPEN(UNIT=11,FILE=FNAME,STATUS='OLD',ERR=999)
        READ(11,FMT='(I4)')NPOINTS
        IF (NPOINTS.GT.1000) GOTO 1000
        PRINT *,'MAIN:POINTS TO READ: ', NPOINTS
        DO 20,I=1,NPOINTS
            READ(11,'(F10.4)')X(I)
20      CONTINUE
        CALL MEANSD(X,NPOINTS,AVG,SD)
        WRITE(*, '(2(A,F10.4))') 'MEAN:',AVG,' STD DEVIATION:',SD
        CALL MNSD2(X,NPOINTS,AVG,SD)
        WRITE(*, '(A,F10.4)') ' STD DEVIATION 2:',SD
        STOP
999     PRINT *,'MAIN:ERROR IN OPENING INPUT FILE: DOES THE FILE EXIST?'
        GOTO 10
1000    PRINT *,'MAIN:ERROR: THE NUMBER OF POINTS IS TOO BIG'
        STOP
      END
