C CALCULATE THE MEAN OF THE POINTS
      REAL FUNCTION MEAN(X,NPOINTS)
        IMPLICIT NONE
        INTEGER NPOINTS,I
        REAL X(10000),MSUM
        MSUM = 0.0
        DO 10,I=1,NPOINTS
            MSUM=MSUM+X(I)
10      CONTINUE
        MEAN=MSUM/NPOINTS
        RETURN
      END
C STANDARD DEVIATION POPULATION
      SUBROUTINE SIGMA(X,NPOINTS,AVG,SD)
        IMPLICIT NONE
        INTEGER NPOINTS,I
        REAL X(10000),AVG,SD,MVAR,MEAN
        AVG=MEAN(X,NPOINTS)
        MVAR=0.0
        DO 20,I=1,NPOINTS
            MVAR=(X(I)-AVG)**2+MVAR
20      CONTINUE
        WRITE(*, '(A,F10.4)') 'SIGMA:VARIANCE:',MVAR/NPOINTS
        SD=SQRT(MVAR/NPOINTS)
      END
C STANDARD DEVIATION ON THE SAMPLE
      SUBROUTINE S(X,NPOINTS,AVG,SD)
        IMPLICIT NONE
        INTEGER NPOINTS,I
        REAL X(10000),AVG,SD,MVAR,MEAN
        AVG=MEAN(X,NPOINTS)
	MVAR=0.0
        DO 10,I=1,NPOINTS
            MVAR=(X(I)-AVG)**2+MVAR
10      CONTINUE
        WRITE(*, '(A,F10.4)') 'SAMPLE:VARIANCE:',MVAR/(NPOINTS-1)
        SD=SQRT(MVAR/(NPOINTS-1))
      END

      SUBROUTINE SIGMAT(X,NPOINTS,AVG,SDT)
        IMPLICIT NONE
        INTEGER NPOINTS,I
        REAL X(10000),AVG,SDT,MSUM,MQSUM
        MSUM=0.0
        MQSUM=0.0
        DO 10,I=1,NPOINTS
            MSUM=X(I)+MSUM
            MQSUM=X(I)**2+MQSUM
10      CONTINUE
        SDT=SQRT((1.0/NPOINTS)*MQSUM-((1.0/NPOINTS)*MSUM)**2)
      END
C main program
      PROGRAM STATS
        IMPLICIT NONE
        CHARACTER FNAME*16
C MAX N. OF POINTS ALLOWED IS 1000
        REAL X(10000),AVG,SD,MEAN
        INTEGER NPOINTS,I
10      WRITE(*,*)'ENTER DATA FILE NAME'
        READ(*,*)FNAME
        OPEN(UNIT=11,FILE=FNAME,STATUS='OLD',ERR=999)
        READ(11,FMT='(I8)')NPOINTS
        IF (NPOINTS.GT.10000) GOTO 1000
        PRINT *,'MAIN:POINTS TO READ: ', NPOINTS
        DO 20,I=1,NPOINTS
            READ(11,'(F10.4)')X(I)
20      CONTINUE
        AVG=MEAN(X,NPOINTS)
        WRITE(*, '(A,F10.4)') 'MEAN:',AVG
        CALL SIGMA(X,NPOINTS,AVG,SD)
        WRITE(*, '(A,F10.4)') 'STANDARD DEVIATION:',SD
        CALL S(X,NPOINTS,AVG,SD)
        WRITE(*, '(A,F10.4)') 'Sample STANDARD DEVIATION:',SD
        WRITE(*, '(A,F10.4)') 'relative sigma:',SD/ABS(AVG)
        CALL SIGMAT(X,NPOINTS,AVG,SD)
        WRITE(*, '(A,F10.4)') 'Mean:',AVG
        WRITE(*, '(A,F10.4)') 'STANDARD DEVIATION2:',SD
        WRITE(*, '(A,F10.4)') 'relative sigma2:',SD/ABS(AVG)
        STOP
999     PRINT *,'MAIN:ERROR IN OPENING INPUT FILE: DOES THE FILE EXIST?'
        GOTO 10
1000    PRINT *,'MAIN:ERROR: THE NUMBER OF POINTS IS TOO BIG'
        STOP
      END
